### ISSUE TITLE
Item::parent() not return the parent category of current item instance

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#104]
This happening in the "sendPushNotification" observer during the feed update, where various items are created :
```
  public static function sendPushNotification($self, $params, $chain)               
  {                                                                                 
    $item = $params['entity'];                                                      
    $category = $item->parent();                                                    
    // only if new and category send notifications                                  
    if (!$item->id() && $item->is_published && $category->notification) {           
      $chain = $chain->next($self, $params, $chain); // save the item               
      if ($id = $item->id()) {                                                      
        WorkerManager::enqueue('push_notification',  ['item_id' => $id, 'category_id' => $category->id]);
      }                                                                             
      return $chain;                                                                
    }                                                                               
    return $chain->next($self, $params, $chain);                                    
  }
```
It returns the category of the first instance of an Item object:
```
  public function parent($entity) {                                                                                                                                                                  
    if ($this->parent) return $this->parent;                                                                                                                                                         
    return $this->parent = Model::load('Categories')->firstById($entity->parent_id);                                                                                                                 
  }
```

**Comment by elbidone** [comment]
If think this issue is redundant with #81. Should investigate if yes and merge informations on previous if true. 

# What occurs
When update_feeds is called if the first extension processed is related to a category with push enabled all next extensions processed on this thread will be considered as Push-enabled.
The inverse also works, if the first extension processed is related to a category with push disabled all next extensions processed on this thread will be considered as Push-disabled.

# How to reproduce
To reproduce you should check on which order extensions are retrieved by update_feeds. And enable/disable Push on first processed. After that check on logs that all next categories processed follow same behavior of first.
To reproduce RSS feeds should have new items to be created.

# why it happens
> Item::parent() not return the parent category of current item instance

# How to fix
@juliogreff can you check it ?
