### ISSUE TITLE
Cannot deselect all options of a multiselect on items and visitors forms

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#23]
This is happening on  groups and related product multiselects.

When unselect all options at once and save, the options are still selected

Replace the chosen plugin with the select2 fork. That besides fix this, also allow add new options dynamically

**Comment by t4deu** [comment]
Turns out , that this isn't a bug of the plugin.

If no value is selected on a multiselect form input, the field is removed from the request by default, like what happens with "checkbox".
http://stackoverflow.com/questions/3363952/how-do-i-allow-a-user-to-select-zero-options-from-a-multiple-selection-box-in-ra

And since the property isn't present on the request, it is not updated in the object(Item or Visitor) 

A easy fix is to add a hidden input with a empty value of the property, like what is done for checkbox:

**Comment by elbidone** [comment]
It raises a new bug, please TEST!!!
* or show us how to deselect all options, I can't achieve it on chrome or safari
* and tell us why when we create a new item without selecting any group it save
"groups" : "" instead of "groups" : [ ] ? see on INT ObjectId("55143e5ab5a508303a8b4567")

Because of this new issue the created item never appears when we call items on api
https://www.evernote.com/shard/s245/sh/4c4a67ab-330b-47cd-a1ff-62b1c9316c6c/3b8623483bc1c3c70017488296e6f0a6/deep/0/Index---MeuMobi.png

**Please TEST!!!!!! It's not normal to close a not fixed issue and raise a new one.**
