### ISSUE TITLE
on visitors/group multi-select, allow to add new entries

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#25]
when I create new visitors, admin should be able to create a new entry on group's list.

This option should be only available on /visitors/add, not on /items/add (there's no meaning to share an article for empty group of visitors)
If it's complex to have 2 different behaviors (/visitors/add allow to add group & /items/add not allow to add group) then you can let the same behavior fo both. So Please explain on this issue how to manage this situation.

**Comment by t4deu** [comment]
Since the /visitors/add and itens/add use different helpers(ItemsHelper, FormHelper) it's easy to apply the behavior to just one of them.

Add the flag attribute "allow-add" to the visitors group multiselect.

    <select  multiple data-allow-add></select>

And configure select2 plugin, to enable the creation only for those flagged, use the "createSearchChoice" callback:
sample: http://jsfiddle.net/XQ8Fw/

    $("select[multiple][data-allow-add]").select2({
      createSearchChoice: function() ....
    });
