### ISSUE TITLE
Monitor the platform with VisualPing

### ISSUE THREAD

**Issue by juliogreff** [meumobi/sitebuilder#356]
Things we want to monitor:

* API endpoints for important sites, check if they reply with valid JSON
* Age of oldest job in the queue

**Comment by elbidone** [comment]
Below the main issues we faced on latest months to find a solution how we can monitor them:

- feeds are not imported (during 24h, I didn't find the issue on github): ...
- meumobi is not reachable (due to comma missing on config.php): ...
- #336 all requests api returns 500:  **for important sites, check if they reply with valid JSON**
- #335 push not sent: **monitor de age of oldest job in queue**
- #337 media.url are wrong, domain has disappeared: ...
- #326 all sites are redirected to home meumobi.com: **for important sites, check if they reply with valid JSON**
- #321 GET /api/visitors returns 500 instead of 401 if not logged: **for important sites, check if they reply with valid response code**

**Comment by juliogreff** [comment]
@elbidone which are the important sites we want to monitor?

**Comment by elbidone** [comment]
You'll find below a list of sites important to monitor because they represent various different configurations, segment and access policy.

domain | segment | access
---- | ---- | ----
180back.meumobi.com | enterprise | public
infobox.meumobi.com | infobox | private
cieloen.mobi.comunique-se.com.br | investors | public
dnadigital.meumobi.com | comunique-se | private

**Comment by elbidone** [comment]
here a good example of monitoring we are looking for, from [http://status.build.phonegap.com/](http://status.build.phonegap.com/)

**Comment by elbidone** [comment]
Interesting post about this topic: https://blog.toggl.com/2014/04/5-tips-servers-service-monitoring/
