### ISSUE TITLE
each time I save an event it wrongly convert dates

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#421]
I've manually created an event with start and end dates resp. 18h21 and 18h20.
I've reopened it and it shows 13h21 and 13h20.  Seems to display or save on different timezone.

**Comment by elbidone** [comment]
The timezone is setted on /sites/general page and saved on site table.
It seems to work fine when events are saved from feeds (sitebuilder/config/schedule.rb)

**Comment by marcosalm** [comment]
Hi @elbidone, it seems that the problem is the php configuration .... the default system time zone is "UTC", and all data is stored perfectly, but when the data is retrieved, and passes the FormHelper class, method:
`protected function value($name)
	{
		$value = '';
		if ($model = $this->model()) {
			if ($model->hasAttribute($name)) {
				$value = $model->{$name};
			} else if ($model->hasGetter($name)) {
				$value = $model->{$name}();
			}

			if ($value instanceof MongoDate) {
				$timezone = date_default_timezone_get();
				date_default_timezone_set($this->view->controller->getCurrentSite()->timezoneId());
				$value = date('Y-m-d\TH:i', $value->sec);
				date_default_timezone_set($timezone);
			}
		}

		return $value;
	}`

when is changed the timezone, for display the date, it changes from "UTC"(the system format), for the one saved in the settings. That's why it's happening this bug.

My sugestions are: Or set the application's timezone with the one that was choosed in the settings. Or actually just remove the timezone change in the method above, since the date saved is exactly the one edited by the user.

**Comment by elbidone** [comment]
Ok, then I believe the issue is on save... Because if I save an event at 6pm on my site (tz=Sao Paulo), it **should be saved on UTC** (9pm). If I open it meumobi should also convert it to my tz to display 6pm. 
This behavior should be the same on import, if date format provide tz then use it, if not consider the settings of site.
On RSS import the tz is setted, because it should follows [RSS 2.0 recommendation](http://www.rssboard.org/rss-draft-1#data-types-datetime), see an [example](http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=NcDSh23/YI0Lheongw5msw==&tp=0).

On UpdateEventsFeedWorker the format didn't include tz, so it should use the tz setted on site settings, see an [example](http://cielo.riweb.com.br/FeedMeuMobi.aspx?idCanal=JGUOaG8NSAkQD94cW6XdAw==&tp=1).

We didn't observe any issue from API, be careful, but I don't know if it's because it works or because the combination of 2 issues make it works good ;-)

@juliogreff please provide use some insights, I know that's a sensitive issue.

**Comment by marcosalm** [comment]
@elbidone, i waited for @juliogreff response. But digging around i fouind out a more simple solution.

In bootstrap.php i added a function for loading the timezone from database and setting it as default...
since mongodb convert to UTC by default any date, and without setting the timezone, the mongodb driver seems to be saving the date passed as UTC, so when we retrieve it , it changes to other values as we apply the selected timezone in setiings... Adding this function to bootstrap, now all the aplication when started by default is in the timezone selected by the user. so when it saves any date now... it convert from the selected timezone to UTC, and when retrive convert back to the timezone. Let me know if you want me to submit the code.

**Comment by elbidone** [comment]
@juliogreff does it make sense for you ?
