### ISSUE TITLE
nominate a category on latest feed

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#422]
On current release all categories are "nominated" on /latest endpoint.
We'd like to define which categories should appears on /latest endpoint. By this way we'll can exclude for instance contacts or jobs of /latest feed.
Please consider 2 options, we'll choose depending on complexity:
- set as category property, ie. latest_feed. Configurable on category Options
- select item's type to be included on /latest feed. For example include articles and events but not contacts.

**Comment by marcosalm** [comment]
Hi @elbidone, well, digging in the code, I found that both options have no complexity, they are easy to be done. But, using the solution which is defined Property category options is a little easier than creating a place to select the category to send the latest feeds. Since only need to update the table of categories in mysql with the "latest_feed" show it in the category options page and the back-end, change the line:
`$categories = Model::load('Categories')->allBySiteIdAndVisibility($this->site()->id, 1);`
by
`$categories = Model::load('Categories')->allBySiteIdAndVisibilityAndLatestFeed($this->site()->id, 1,1); `
I think that would solve the "problem".

**Comment by elbidone** [comment]
o, so go on 1st option, set a category property

**Comment by elbidone** [comment]
by default set true to maintain current behaviour
