### ISSUE TITLE
allow to add pdf from web on items[type=article]

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#44]

**Comment by t4deu** [comment]
Add the media Title, url imputs, and a hidden media type input with the value "application/pdf" to the items form.

The values will be automatically assigned to the item object at the items/add and items/edit controller actions.

But since the media file size ins't provided by the user, add a beforeSave method to the app/models/Items.php. It should set the file size of medias if it isn't already set, making the a request to the file url and use the Content-Length header as the value.

But the request will not get the body of the response, only it's headers, making the request a lot faster, check here how to do: http://stackoverflow.com/questions/2602612/php-remote-file-size-without-downloading-file

**Comment by t4deu** [comment]
Updating the previous comment.
Instead of make the request in the before save method(addMediaFileZise), use the method to create a job for the MediaFileSizeWorker. The worker will make the request and update the media file size.

The MediaFileSizeWorker must implement the "perform()" method like the GeocodeWorker.

**Comment by t4deu** [comment]
The media form is complete and working, but still need to add a way to remove the files. like a remove button or link.
I'm not sure of which UX to use.

The INT was updated.

**Comment by elbidone** [comment]
no matter the UX will be you can add the feature. Try to be consistent in terms of implementation and UX.

**Comment by elbidone** [comment]
Add a validation on form, media.title and media.url are required
Do it consistent with others forms on site-builder
The removing link should have the same behavior as /sites/custom_domain

**Comment by t4deu** [comment]
I will also add the validation to the item itself, currently there is no validation, an item can be created without title, site, category etc.

I gonna use the Lithium validation if possible
