### ISSUE TITLE
Unable to to call PUT /visitors wihtout header X-Visitor-Token

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#47]
The behavior of not-documented endpoint /visitors (see #26) has changed.
I should be able to call it wihout header "X-Visitor-Token". On current version it raises a Response Code 401.

Request URL:http://int-meumobi.com/api/infobox.int-meumobi.com/visitors/login
Request Method:POST
{"token":"b43954d10f7e80e39fc6978e02ecf1155a668df1","visitor":{"first_name":"Victor","last_name":"Dias","email":"victor.dias@ipanemax.com"},"error":"password expired"}

When there's an error I recommend to not return the token, because it couldn't be used.

**Comment by juliogreff** [comment]
Maybe the status code I chose as the return value isn't very clear.

What happens is, you've been authenticated (that's why there's the token), but since your password should be renewed, you need to update it immediately (hence the "error": "password expired").

We might find a better way to handle this, but the feature works, so I'm retagging the issue to "enhancement" instead of bug. Any suggestion on how to handle this case differently?
