### ISSUE TITLE
ENHANCE: disable limit of items by category if import mode is exclusive

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#548]
If import mode is exclusive we must save all items from Feed

**Comment by elbidone** [comment]
On current version articles_to_keep is setted to 999 if notification enabled on category. If not, the category is limited to 50 items (ARTICLES_TO_KEEP)

```
protected function extractArticles($feed, $category, $purify)
    {
	$limit = $category->notification?999:self::ARTICLES_TO_KEEP;
	// gets last n items, most recent last
        $items = array_slice(array_reverse($feed->get_items()), -$limit);
```
But It should raise an issue if you enable notification.
To prevent this issue we should **remove the limit if mode is exclusive**.
**/!\ Be careful: on migration disable push**

**Comment by elbidone** [comment]
Should test if we update through UI the import mode if it process data as priority high then prevent push

**Comment by danconte72** [comment]
Every time a extension is updated by UI the priority is also updated to HIGH  
Before Test
![image](https://user-images.githubusercontent.com/32454870/37288812-f41cdde8-25e6-11e8-89eb-2b544f397918.png)
After Test
![image](https://user-images.githubusercontent.com/32454870/37288848-0a21b474-25e7-11e8-95b1-05c1e029e3d9.png)

**Note:** If checksum is update, the priority is not lowered un UpdateNewsFeed because its is set after the check
