### ISSUE TITLE
why several pid files for importEmail ?

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#581]
![sitebuilder_ _ssh_root_meumobi_com_ _95x41_and_search_logs___scalyr](https://user-images.githubusercontent.com/9011612/38194041-184cca3e-366d-11e8-80f7-acaa86882f81.png)

**Comment by danconte72** [comment]
Because on [schedule](https://github.com/meumobi/sitebuilder/blob/0bacd0b257ae1686844bfb61986c3f4ba6ad8123/sitebuilder/config/schedule.rb#L16) there was not lock informed;
If there is no lock [uniqid](https://github.com/meumobi/sitebuilder/blob/0bacd0b257ae1686844bfb61986c3f4ba6ad8123/sitebuilder/script/run_worker.php#L15) is generated;
