### ISSUE TITLE
extension.priority is removed if not 1

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#70]
It only exists extension.priority=1 not extension.priority=0, why ?

On CSE
```mongo
> db.extensions.find({priority: 1}).count();
13
> db.extensions.find({priority: 0}).count();
0
> db.extensions.count();
206
>
```

**Comment by t4deu** [comment]
Currently the priority of a extension is defined by the existence of the "priority" attribute, not it's value

**Comment by juliogreff** [comment]
That is a bit of surprising behavior, we should change that to actually look at the value, and fall back only if the value is not there

**Comment by elbidone** [comment]
The bug is bigger than that, the whole implementation of priority is "exotic", despite a simple specification.

### Specification
EACH extension should have a priority field.
It exists 3 levels of priority, see below "sitebuilder/app/models/extensions/Rss.php"

```php
class Rss extends Extensions
{
  const ARTICLES_TO_KEEP = 50;
  const PRIORITY_HIGH = 2;
  const PRIORITY_MEDIUM = 1;
  const PRIORITY_LOW = 0;
```

When  a feed is new or all feed.items have been removed the priority is HIGH.
When feed has been processed the priority change to LOW.
We don't use MEDIUM now, but no need to remove it.

### Implementation
1/ The implementation define priorities on several layers (DRY), as shown above on "sitebuilder/app/models/extensions/Rss.php" and:

sitebuilder/lib/meumobi/sitebuilder/services/Service.php
```php
abstract class Service
{
  const PRIORITY_LOW = 0;
  const PRIORITY_HIGH = 1;
...
```

2/ It removes priority instead of changing it from HIGH to LOW
3/ It doesn't search for HIGH priority but for "priority >= 1" ?!?, see sitebuilder/lib/meumobi/sitebuilder/services/Service.php below

```php
  protected function priorityCriteria()
  {
    $priorities = [
    self::PRIORITY_HIGH => ['$gte' => 1],
    self::PRIORITY_LOW => ['$exists' => false],
    ];

    return $priorities[$this->options['priority']];
  }
```

### Conclusion
To resume the implementation doesn't follow the specification and is full of inconsistencies. I think easier to implement the specification and will save a lot of debugging time in the future.

**Comment by t4deu** [comment]
Currently the feed import implementation is splitted on several places.

The script "update_feeds.php" calls UpdateFeedsService, that list the Rss Extensions, and for each extension it calls the "updateArticles" method, and inside this method the Articles::addToFeed, the one that actually import the item, is called, uuaauuu.

Also note that the Rss extension is the only one that is implementing the import, the others extensions(EventFeed, GoogleMerchantFeed etc.) are used only to store settings, the import is made at the Async Service level.

To fix this and implement what already was discussed on the issues #70, #68 and #67, we need:

1. Replace the UpdateFeedsService for UpdateFeedsWorker.#67
2. Move all that splitted implementation to the Worker
3. Clean the Rss extension, to store only settings
4. Split the old Articles::addToFeed into UpdateFeedsWorker::getItem and UpdateFeedsWorker::updateItemFromFeed() #68
6. Self enqueue the UpdateFeedsWorker based on the extension.priority setting value

This will clean a lot of things, the Article model for example will be simplified, and this is also good because replace the old sitebuilder implementation for the new and more modular one.

**Comment by t4deu** [comment]
Making use of log levels, the logs will be.

Info Logs:
* Extension Id
* Category Id
* Priority

Debug Logs:
* Total Articles
* Removed Articles
* Imported Articles ids
* Removed Articles ids
* Total Images
Failed Images
* Total Feeds
* Failed Feeds

Error Logs:
* Invalid Feed Url
* Invalid Extension Category
