### ISSUE TITLE
items/latest should retrieved items sorted by published date and not created date

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#92]

**Comment by t4deu** [comment]
I think it has already been done, as commented on #72

**Comment by elbidone** [comment]
The #72 concerns wrong created date not sort. On prod items/latest are
sorted by created date
 Em 22/05/2015 08:35, "t4deu" <notifications@github.com> escreveu:

**Comment by t4deu** [comment]
Ok, but I think that what Julio  asked me to on the #72 comments yesterday, was exactly this:

https://github.com/meumobi/sitebuilder/issues/72#issuecomment-104253029
*You might also need to update the API for the ItemsController::latest(), since it currently uses the creation date for ordering. We need to change that to use the date the item was published on.*

**Comment by elbidone** [comment]
Yes but you didn't open an issue for it as expected. It's what I've done.
And it's why I don't understand your comment.
Em 22/05/2015 12:13, "t4deu" <notifications@github.com> escreveu:
